#language: node_js
#node_js:
  #- lts/*
#script:
  #- npm run build
#deploy:
  #provider: pages
  #skip-cleanup: true
  #local_dir: .vuepress/dist
  #github-token: ${GH_TOKEN} # a token generated on github allowing travis to push code on you repository
  #keep-history: true
  #on:
    #branch: master


language: node_js
env:
  global:
  - GH_REF: github.com/chenfjm/jsm.git
branches:
  only:
  - master
sudo: false
node_js: stable
cache:
  directories:
  - node_modules
before_install:
  - git config --global user.name "chenfjm"
  - git config --global user.email "chenfjm@gmail.com"
install:
  - npm install
script:
  - npm run build
after_script:
 - cd .vuepress/dist
 - git init
 - git add .
 - git commit --message "Automatically update from travis-ci"
 - git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

